# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
before_install:
- brew update
- brew install swiftformat
- brew outdated carthage swiftlint || brew upgrade carthage swiftlint
script:
- swiftformat --lint --verbose .
- swiftlint
- xcodebuild test -enableCodeCoverage YES -scheme JavaScriptSwift-Package
after_success:
- bash <(curl -s https://codecov.io/bash)
